name: Publish NuGet

on:
  # This will only be required during testing.
  pull_request:
  push:
    branches:
      - master

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Read Version
        id: version
        run: |
          version=`cat ./version.txt`
          echo "::set-output name=version::$version"
      - name: Bump Bug
        if: "!contains(${{steps.version.outputs.version}}, 'alpha') && !contains(${{steps.version.outputs.version}}, 'beta')"
        id: bump-bug
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{env.NUGET_VERSION}}
          version-fragment: bug
      - name: Set NuGet version from bug.
        if: "!contains(env.NUGET_VERSION, 'alpha') && !contains(env.NUGET_VERSION, 'beta')"
        run: echo "::set-env name=NUGET_VERSION::${{steps.bump-bug.outputs.next-version}}"
      - name: Tell me the version
        run: echo ${{ env.NUGET_VERSION }}
      # - name: Bump Alpha
      #   if: "contains(env.NUGET_VERSION, 'alpha')"
      #   id: bump-alpha
      #   uses: christian-draeger/increment-semantic-version@1.0.2
      #   with:
      #     current-version: ${{env.NUGET_VERSION}}
      #     version-fragment: "alpha"
      # - name: Bump Beta
      #   if: "contains(env.NUGET_VERSION, 'beta')"
      #   id: bump-beta
      #   uses: christian-draeger/increment-semantic-version@1.0.2
      #   with:
      #     current-version: ${{env.NUGET_VERSION}}
      #     version-fragment: "beta"
      # - name: Echo Version
      #   run: echo ${{ env.NUGET_VERSION }}
      # - run: dotnet build -c release -p:Version=${{ steps.version.outputs.content }}
      # - name: Publish Elements
      #   run: echo "You made it to the end!"
