name: Build Docs

on:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup docfx
        run: choco install docfx -y
      - name: Setup AWS CLI
        run: choco install awscli -y
      - name: Build docs
        run: |
          rm -r docs
          dotnet test --filter Category=Examples
          docfx ./doc/docfx.json -f
      - name: Deploy Docs
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-west-1
          aws sync ./docs s3://${{ secrets.AWS_BUCKET }}
