name: Tag and Publish Alpha

on:
  push:
    branches:
      - master

jobs:
  build-bump-publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Get previous tag.
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Bump if alpha.
        if: ${{contains(steps.version.outputs.tag, 'alpha')}}
        id: bump-alpha
        uses: actions/github-script@v3
        result-encoding: string
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          current-version: ${{steps.version.outputs.tag}}
          script: |
                const incoming = "${{steps.version.outputs.tag}}"
                console.log("Incoming Tag: " + incoming)
                const oldNum = incoming.match(/alpha[.]*(\d+)/)[1]
                const newNum = parseInt(oldNum)+1
                const newTag =incoming.replace(/alpha.*\d+/, `alpha.${newNum}`)
                console.log("New Tag: " + newTag)
                return newTag
      - name: Set NuGet version from alpha.
        if: ${{contains(steps.version.outputs.tag, 'alpha')}}
        run: echo "NUGET_VERSION=${{steps.bump-alpha.outputs.result}}" >> $GITHUB_ENV
      - name: Build Elements
        run: dotnet build -c release -p:Version=${{ env.NUGET_VERSION }}
      - name: Publish NuGet package.
        run: |
          dotnet nuget push ./nupkg/Hypar.Elements.${{ env.NUGET_VERSION }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
          dotnet nuget push ./nupkg/Hypar.Elements.CodeGeneration.${{ env.NUGET_VERSION }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
          dotnet nuget push ./nupkg/Hypar.Elements.Serialization.IFC.${{ env.NUGET_VERSION }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
      - name: Create alpha tag.
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bump-alpha.outputs.result }}
