name: Testing Docs

on:
  push:
    branches:
      - docfx-cicd

jobs:
  build-bump-publish:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup docfx
        run: choco install docfx -y
      - name: Build docs
        run: |
          rm -rf ./docs
          dotnet test --filter Category=Examples
          docfx ./doc/docfx.json -f --serve
      - name: Commit docs
        uses: EndBug/add-and-commit@v7
        with:
          message: "Updated docs for Elements ${{ env.NUGET_VERISION }}"