name: Testing Docs

on:
  push:
    branches:
      - docfx-cicd

jobs:
  build-bump-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup docfx
        run: brew install docfx
      - name: Get previous tag.
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Bump if alpha.
        if: ${{contains(steps.version.outputs.tag, 'alpha')}}
        id: bump-alpha
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{steps.version.outputs.tag}}
          version-fragment: "alpha"
      - name: Set NuGet version from alpha.
        if: ${{contains(steps.version.outputs.tag, 'alpha')}}
        run: echo "NUGET_VERSION=${{steps.bump-alpha.outputs.next-version}}" >> $GITHUB_ENV
      - name: Bump if beta.
        if: ${{contains(steps.version.outputs.tag, 'beta')}}
        id: bump-beta
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{steps.version.outputs.tag}}
          version-fragment: "beta"
      - name: Set NuGet version from beta.
        if: ${{contains(steps.version.outputs.tag, 'beta')}}
        run: echo "NUGET_VERSION=${{steps.bump-beta.outputs.next-version}}" >> $GITHUB_ENV
      - name: Build Elements
        run: dotnet build -c release -p:Version=${{ env.NUGET_VERSION }}
      - name: Build docs
        run: sh ./build_docs.sh
      - name: Commit docs
        uses: EndBug/add-and-commit@v7
        with:
          message: "Updated docs for Elements ${{ env.NUGET_VERISION }}"