name: Publish on Tag Creation

on:
  push:
    tags:
      - '*'

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Get previous tag.
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Set NuGet version from tag.
        run: echo "::set-env name=NUGET_VERSION::${{steps.version.outputs.tag}}"
      - run: dotnet build -c release -p:Version=${{ env.NUGET_VERSION }}
      - name: Publish NuGet package.
        run: |
          dotnet nuget push ./nupkg/Hypar.Elements.${{ env.NUGET_VERSION }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
          dotnet nuget push ./nupkg/Hypar.Elements.CodeGeneration.${{ env.NUGET_VERSION }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
          dotnet nuget push ./nupkg/Hypar.Elements.Serialization.IFC.${{ env.NUGET_VERSION }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
